name: xtra
description: >-
  Some xtra useful datatypes, currently XTable and XSet, a set of XTables are usable.
version: 0.2.3
homepage: https://github.com/DorylinaeStudios/xtra
repository: https://github.com/DorylinaeStudios/xtra
issue_tracker: https://github.com/DorylinaeStudios/xtra/issues
documentation: https://pub.dev/documentation/xtra/latest/

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
